import os from "node:os";
import path from "node:path";
import { APP_NAME, SERVICE_LABEL, defaultServiceEnvFile, defaultStateDir } from "../config.js";

export interface LaunchdConfig {
  label?: string;
  rootDir: string;
  nodeBin: string;
  stateDir?: string;
  envFile?: string;
  stdoutLog?: string;
  stderrLog?: string;
}

export function buildLaunchdPlist(config: LaunchdConfig): string {
  const label = config.label ?? SERVICE_LABEL;
  const stateDir = config.stateDir ?? defaultStateDir();
  const envFile = config.envFile ?? defaultServiceEnvFile();
  const logDir = path.join(stateDir, "logs");
  const stdoutLog = config.stdoutLog ?? path.join(logDir, "service.out.log");
  const stderrLog = config.stderrLog ?? path.join(logDir, "service.err.log");
  const args = [
    config.nodeBin,
    path.join(config.rootDir, "scripts", "service", "run-service.mjs"),
    "--root-dir",
    config.rootDir,
    "--state-dir",
    stateDir,
    "--env-file",
    envFile,
  ];
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${escapeXml(label)}</string>
  <key>ProgramArguments</key>
  <array>
${args.map((arg) => `    <string>${escapeXml(arg)}</string>`).join("\n")}
  </array>
  <key>WorkingDirectory</key>
  <string>${escapeXml(config.rootDir)}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${escapeXml(stdoutLog)}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(stderrLog)}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${escapeXml(os.homedir())}</string>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
</dict>
</plist>
`;
}

export function defaultServiceEnvContent(): string {
  return `# Generated by ${APP_NAME}
WECHAT_BRIDGE_STATE_DIR=${defaultStateDir()}
WECHAT_SEND_API_HOST=127.0.0.1
WECHAT_SEND_API_PORT=55523
WECHAT_SEND_API_ALLOWED_IPS=127.0.0.1,localhost
WECHAT_TARGET_USER_ID=

CODEX_BIN=codex
CODEX_CWD=${process.cwd()}
CODEX_MODEL=
CODEX_PROFILE=
CODEX_SANDBOX=read-only
CODEX_APPROVAL=never
`;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
