#!/usr/bin/env bash
set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "launchd user services are only supported on macOS" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LABEL="${LABEL:-com.ibobby.wechat-bridge-minimal}"
PLIST_DIR="${HOME}/Library/LaunchAgents"
PLIST_PATH="${PLIST_DIR}/${LABEL}.plist"
CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/wechat-bridge-minimal"
STATE_DIR="${WECHAT_BRIDGE_STATE_DIR:-${CONFIG_DIR}/state}"
ENV_FILE="${SERVICE_ENV_FILE:-${CONFIG_DIR}/service.env}"
LOG_DIR="${STATE_DIR}/logs"
NODE_BIN="${NODE_BIN:-$(command -v node)}"

mkdir -p "${PLIST_DIR}" "${CONFIG_DIR}" "${LOG_DIR}"

if [[ ! -f "${ENV_FILE}" ]]; then
  cat > "${ENV_FILE}" <<EOF
# Generated by wechat-bridge-minimal
WECHAT_BRIDGE_STATE_DIR=${STATE_DIR}
WECHAT_SEND_API_HOST=127.0.0.1
WECHAT_SEND_API_PORT=55523
WECHAT_SEND_API_ALLOWED_IPS=127.0.0.1,localhost
WECHAT_TARGET_USER_ID=
WECHAT_TYPING_KEEPALIVE_MS=8000

CODEX_BIN=codex
CODEX_CWD=${ROOT_DIR}
CODEX_MODEL=
CODEX_PROFILE=
CODEX_SANDBOX=read-only
CODEX_APPROVAL=never
EOF
  chmod 600 "${ENV_FILE}" || true
fi

cat > "${PLIST_PATH}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${NODE_BIN}</string>
    <string>${ROOT_DIR}/scripts/service/run-service.mjs</string>
    <string>--root-dir</string>
    <string>${ROOT_DIR}</string>
    <string>--state-dir</string>
    <string>${STATE_DIR}</string>
    <string>--env-file</string>
    <string>${ENV_FILE}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${ROOT_DIR}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>${LOG_DIR}/service.out.log</string>
  <key>StandardErrorPath</key>
  <string>${LOG_DIR}/service.err.log</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${HOME}</string>
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
</dict>
</plist>
EOF

launchctl bootout "gui/${UID}" "${PLIST_PATH}" >/dev/null 2>&1 || true
launchctl bootstrap "gui/${UID}" "${PLIST_PATH}"
launchctl enable "gui/${UID}/${LABEL}"
launchctl kickstart -k "gui/${UID}/${LABEL}"

echo "Installed ${PLIST_PATH}"
echo "Environment file: ${ENV_FILE}"
echo "Logs: ${LOG_DIR}"
